from django.db import models

class F8872(models.Model):
	record_type = models.CharField(max_length=1)
	form_type = models.IntegerField()
	form_id_number = models.CharField(db_index=True,max_length=38)
	begin_date = models.DateField(auto_now=False)
	end_date = models.DateField(auto_now=False)
	initial_report_indicator = models.IntegerField()
	amended_report_indicator = models.IntegerField()
	final_report_indicator = models.IntegerField()
	change_of_address_indicator = models.IntegerField()
	organization_name = models.CharField(max_length=70)
	EIN = models.CharField(max_length=9)
	mailing_address_line_1 = models.CharField(max_length=50, null=True, blank=True)
	mailing_address_line_2 = models.CharField(max_length=50, null=True, blank=True)
	mailing_address_city = models.CharField(max_length=50, null=True, blank=True)
	mailing_address_state = models.CharField(max_length=2, null=True, blank=True)
	mailing_address_zip_code = models.CharField(max_length=5, null=True, blank=True)
	mailing_address_zip_ext = models.CharField(max_length=4, null=True, blank=True)
	email = models.CharField(max_length=150)
	org_formation_date = models.DateField(auto_now=False)
	custodian_name = models.CharField(max_length=50)
	custodian_address_line_1 = models.CharField(max_length=50, null=True, blank=True)
	custodian_address_line_2 = models.CharField(max_length=50, null=True, blank=True)
	custodian_address_city = models.CharField(max_length=50, null=True, blank=True)
	custodian_address_state = models.CharField(max_length=2, null=True, blank=True)
	custodian_address_zip_code = models.CharField(max_length=5, null=True, blank=True)
	custodian_address_zip_ext = models.CharField(max_length=4, null=True, blank=True)
	contact_name = models.CharField(max_length=50, null=True, blank=True)
	contact_address_line_1 = models.CharField(max_length=50, null=True, blank=True)
	contact_address_line_2 = models.CharField(max_length=50, null=True, blank=True)
	contact_address_city = models.CharField(max_length=50, null=True, blank=True)
	contact_address_state = models.CharField(max_length=2, null=True, blank=True)
	contact_address_zip_code = models.CharField(max_length=5, null=True, blank=True)
	contact_address_zip_ext = models.CharField(max_length=4, null=True, blank=True)
	business_address_line_1 = models.CharField(max_length=50, null=True, blank=True)
	business_address_line_2 = models.CharField(max_length=50, null=True, blank=True)
	business_address_city = models.CharField(max_length=50, null=True, blank=True)
	business_address_state = models.CharField(max_length=2, null=True, blank=True)
	business_address_zip_code = models.CharField(max_length=5, null=True, blank=True)
	business_address_zip_ext = models.CharField(max_length=4, null=True, blank=True)
	quarter_indicator = models.IntegerField()
	monthly_report_month = models.IntegerField(null=True)
	pre_election_type = models.IntegerField(null=True)
	election_date = models.DateField(auto_now=False, null=True)
	election_state = models.CharField(max_length=2, null=True, blank=True)
	schedule_a_indicator = models.IntegerField()
	schedule_a_total = models.DecimalField(max_digits=10,decimal_places=2)
	schedule_b_indicator = models.IntegerField()
	schedule_b_total = models.DecimalField(max_digits=10,decimal_places=2)
	insert_datetime = models.DateTimeField(auto_now=False)

